# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      env:
        GITH_EMAIL: ${{ secrets.DUMMY_ADDRESS }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITH_USER: "Kazanami" 
    - run: yarn install
    - run: node main.js
    - run: |
        git config --global user.email ${GITH_EMAIL}
        git config --global user.name ${GITH_USER}
        git commit -m "Update Avater Image"
        git push
        git reset
